version: "3.8"
services:
   AppServer:
      image: jboss/wildfly:latest
      ports:
         - "8080:8080"
   DataBaseServer:
      image: postgres:latest
      env_file:
         - postgres.env
      ports: 
         - "5432:5432"
