version: "3.8"
services:
   AppServer:
      image: jboss/wildfly:latest
      ports:
         - "8080:8080"
   DataBaseServer:
      image: postgres:latest
      environment:
         - POSTGRES_PASSWORD=123456
      ports: 
         - "5432:5432"
      volumes:
         - volDataPostgres:/var/lib/postgresql/data
volumes:
   volDataPostgres:
      name : DataBasePostgres
