version: "3.8"
services:
   DataBaseServer:
      image: postgres:latest
      ports:
         - "5432:5432"
      environment:
         - POSTGRES_PASSWORD=123456
   AppServer:
      image: tomcat:latest
      ports:
         - "8080:8080"
networks:
   default:
      external:
         name: mired