version: "3.8"
services:
   Postgres:
      image: miguelangeltimanapaz/postgres_clientone_homebacking:latest
      ports:
         - "5432:5432"
      environment:
         - POSTGRES_PASSWORD=123456
      volumes:
         - VolumePostgres:/var/lib/postgresql/data
   Redis:
      image: redis:latest
      ports:
         - "6379:6379"
      volumes:
         - VolumeRedis:/data
   Mongo:
      image: miguelangeltimanapaz/mongo_clientone_homebacking:latest
      ports:
         - "27017:27017"
      volumes:
         - VolumeMongoData:/data/db
         - VolumeMongoConfig:/data/configdb
      environment:
         - MONGO_INITDB_ROOT_USERNAME=home_backing
         - MONGO_INITDB_ROOT_PASSWORD=123456
         - MONGO_INITDB_DATABASE=home_backing
   Elasticsearch:
      image: elasticsearch:7.6.2
      ports:
         - "9200:9200"
         - "9300:9300"
      environment:
         - discovery.type=single-node
   Kibana:
      image: kibana:7.6.2
      ports:
         - "5601:5601"
volumes:
   VolumePostgres:   
      name: PostgresClientOneHomeBacking
   VolumeRedis:
      name: RedisClientOneHomeBacking
   VolumeMongoData:
      name: MongoDataClientOneHomeBacking
   VolumeMongoConfig:
      name: MongoConfigClientOneHomeBacking
